### ISSUE TITLE
Support math expressions

### ISSUE THREAD

**Issue by clayrisser** [sphinx-contrib/restbuilder#26]
It would be nice if it could support math expressions. For example . . .

```rst
.. math::

   E = m c^2
```

It should generate the image and reference the math image in the rst

**Comment by macfreek** [comment]
Hi, thanks for raising this issue!

I had a quick look, and `.. math::` is a standard directive since docutils 0.8, so I hope it is possible to simply output this as-is, without conversion. I have not looked how Sphinx translates this directive to a doctree. I will try to have a look in the next weekend, or the week thereafter. Feel free to remind me (with a @macfreek tag) if I haven't reported by that time.

**Comment by macfreek** [comment]
It seems this was an easy fix. Can you test if the latest version works as requested?

To install the latest developer version, run:

    git clone https://github.com/sphinx-contrib/restbuilder.git
    cd restbuilder
    python setup.py install

Let me know if it works, and if you need this feature in an automated workflow somewhere. If so, I will consider releasing a bug-fix version. Otherwise, it will be part of a feature release some time in the future.

**Comment by clayrisser** [comment]
Ok sure I'll check. Thanks @macfreek

**Comment by macfreek** [comment]
I'm going to close this ticket. If there is any remaining issue, please don't hesitate to reopen it.
