### ISSUE TITLE
nested list bug: missing line breaks with compact_paragraph

### ISSUE THREAD

**Issue by rvalyi** [sphinx-contrib/restbuilder#27]
Hello, using the rest extension to output the content from https://github.com/odoo/documentation-user, I get rst outputs with wrong nested list. For instance, for _build/rst/accounting.rst I would get something like

```
Invoicing and Accounting
************************

*  Overview
   *  Main Concepts
      *  `The Accounting behind Odoo
         <accounting/overview/main_concepts/in_odoo.rst>`_
      *  `Accounting Memento For Entrepreneurs (US GAAP)
         <accounting/overview/main_concepts/memento.rst>`_
   *  Getting Started
      *  `Initial setup of Odoo Accounting and Odoo Invoicing
         <accounting/overview/getting_started/setup.rst>`_
      *  `Chart of Accounts
         <accounting/overview/getting_started/chart_of_accounts.rst>`_
   *  Process overview
      *  `From Customer Invoice to Payments Collection
         <accounting/overview/process_overview/customer_invoice.rst>`_
      *  `From Vendor Bill to Payment
         <accounting/overview/process_overview/supplier_bill.rst>`_
*  Account Receivables
   *  Customer Invoices
      *  `Overview of the invoicing process
         <accounting/receivables/customer_invoices/overview.rst>`_
      *  `Offer cash discounts
         <accounting/receivables/customer_invoices/cash_discounts.rst>`_
```

The problem is - unless I'm wrong - nested lists should have extra line breaks to reflect the proper structure, like instead:

```

Invoicing and Accounting
************************

*  Overview

   *  Main Concepts

      *  `The Accounting behind Odoo
         <accounting/overview/main_concepts/in_odoo.rst>`_
      *  `Accounting Memento For Entrepreneurs (US GAAP)
         <accounting/overview/main_concepts/memento.rst>`_

   *  Getting Started

      *  `Initial setup of Odoo Accounting and Odoo Invoicing
         <accounting/overview/getting_started/setup.rst>`_
      *  `Chart of Accounts
         <accounting/overview/getting_started/chart_of_accounts.rst>`_

   *  Process overview

      *  `From Customer Invoice to Payments Collection
         <accounting/overview/process_overview/customer_invoice.rst>`_
      *  `From Vendor Bill to Payment
         <accounting/overview/process_overview/supplier_bill.rst>`_

*  Account Receivables

   *  Customer Invoices

      *  `Overview of the invoicing process
         <accounting/receivables/customer_invoices/overview.rst>`_
      *  `Offer cash discounts
         <accounting/receivables/customer_invoices/cash_discounts.rst>`_
```

At least that's what I could check on http://rst.ninjs.org 

Also if you want to try to compile https://github.com/odoo/documentation-user, yourself, I had to comment the line 404 ´self.log_message('Column or row spanning cells are not implemented.')´ and replace it by pass, because there seem to be no such log_message method or not anymore.
sphinxcontrib/writers/rst.py

**Comment by macfreek** [comment]
Thanks for the report, I'll try to have a look and release a fix within 1 or 2 weeks.

**Comment by macfreek** [comment]
Thanks for your report, @rvalyi!

I just pushed a commit to master that should fix these two issues.
`log_message` was a stupid mistake (reminder to self: add `flake8` tests), introduced two commits ago.

The missing line break required me to dive a bit deeper. It turns out that this nested toctree produces a doctree with a `compact_paragraph`. That's a new one to me, so far I encountered only `paragraph`s. So far, restbuilder handled this by creating a paragraph without a line break. That caused the error. I tried to look up the specs for compact_paragraph, but strangely, it is not mentioned on https://docutils.sourceforge.io/docs/ref/doctree.html.

I solved this by letting the `compact_paragraph` behave the same a `paragraph`. In spite of a counter-example, this seems the best behaviour for now.

Just in case this has any adverse effects, I changed the title to contain the word compact_paragraph, and I also added a test case with a nested toctree, to ensure that any future changes makes sure this is handled properly.

This new behaviour will be released in the next release, but I'm holding that for a little while to make sure this change does not cause any unintended side-effects. In the mean time, you can install the latest developer version using:

    git clone https://github.com/sphinx-contrib/restbuilder.git
    cd restbuilder
    python setup.py install

I appreciate feedback if this solves your issues, and please report any other issue you may encounter. `restbuilder` is slowly adding more tests, and reports like this certainly help making it more robust! Thanks!

**Comment by macfreek** [comment]
@rvalyi I'm going to close this by lack of feedback. I hope it now works for you.

Anyone reading this: I still appreciate any reports on the new behaviour of `compact_paragraph`s. If there is any issue, don't hesitate to re-open this ticket.
